
<!----- POPUP DIV BEG -------------------->
<div id="divPopBlank" style="display:none;"></div>
<div id="divPopShade" ></div>
<div id="divPopOuter"  style="display:none; background-color:white;" >
    <div id="divPopTop" style="width:100%; height:25px; background-color: #0054E2; color:#FFFFFF;">
        <div id="divPopTitle" style="float:left;height:100%; font-size:14pt;"></div>
        <div style="float:right; height:100%"><input id="popupX" type="button" value="X" onclick="popupDo();"></div>
    </div>
    <div id="divPopStuff" style="width:100%; background-color:white;"></div>
</div>    
<!----- POPUP DIV END -------------------->
